---
version: '3.9'
services:
  api:
    build: .
    ports:
    - ${WEDNE_PORT}:${WEDNE_PORT}
    command: python -m wedne.server run_api
    environment:
      WEDNE_MINUTES_TO_ORDER: $WEDNE_MINUTES_TO_ORDER
      WEDNE_SECONDS_OF_DELAY: $WEDNE_SECONDS_OF_DELAY
      WEDNE_MINUTES_OF_LAST_ACTIVITY: $WEDNE_MINUTES_OF_LAST_ACTIVITY
      WEDNE_TOWER: $WEDNE_TOWER
      WEDNE_JOB_QUEUE_DATABASE: /var/wedne/jobs.db
      WEDNE_APP_DATABASE: /var/wedne/wedne.db
      WEDNE_HOST: 0.0.0.0
      WEDNE_PORT: $WEDNE_PORT
    volumes:
    - data:/var/wedne

  task-consumer:
    build: .
    command: python -m wedne.server consume_tasks
    environment:
      WEDNE_MINUTES_TO_ORDER: $WEDNE_MINUTES_TO_ORDER
      WEDNE_SECONDS_OF_DELAY: $WEDNE_SECONDS_OF_DELAY
      WEDNE_MINUTES_OF_LAST_ACTIVITY: $WEDNE_MINUTES_OF_LAST_ACTIVITY
      WEDNE_TOWER: $WEDNE_TOWER
      WEDNE_JOB_QUEUE_DATABASE: /var/wedne/jobs.db
      WEDNE_APP_DATABASE: /var/wedne/wedne.db
      WEDNE_HOST: 127.0.0.1
      WEDNE_PORT: $WEDNE_PORT
    volumes:
    - data:/var/wedne

volumes:
  data:
