---
version: '3.9'
services:
  api:
    build: .
    ports:
    - ${WEDNE_HOST}:${WEDNE_PORT}:${WEDNE_PORT}
    command: python -m gunicorn -c wedne/server/gunicorn.py wedne.server.api:app
    environment:
      WEDNE_MINUTES_TO_ORDER: $WEDNE_MINUTES_TO_ORDER
      WEDNE_SECONDS_OF_DELAY: $WEDNE_SECONDS_OF_DELAY
      WEDNE_MINUTES_OF_LAST_ACTIVITY: $WEDNE_MINUTES_OF_LAST_ACTIVITY
      WEDNE_TOWER: $WEDNE_TOWER
      WEDNE_REDIS: redis://redis:6379/0
      WEDNE_APP_DATABASE: /var/wedne/wedne.db
      WEDNE_HOST: 0.0.0.0
      WEDNE_PORT: $WEDNE_PORT
      WEDNE_WORKERS: $WEDNE_WORKERS
    volumes:
    - data:/var/wedne

  task-consumer:
    build: .
    command: python -m wedne.server consume_tasks
    environment:
      WEDNE_MINUTES_TO_ORDER: $WEDNE_MINUTES_TO_ORDER
      WEDNE_SECONDS_OF_DELAY: $WEDNE_SECONDS_OF_DELAY
      WEDNE_MINUTES_OF_LAST_ACTIVITY: $WEDNE_MINUTES_OF_LAST_ACTIVITY
      WEDNE_TOWER: $WEDNE_TOWER
      WEDNE_REDIS: redis://redis:6379/0
      WEDNE_APP_DATABASE: /var/wedne/wedne.db
      WEDNE_HOST: 127.0.0.1
      WEDNE_PORT: $WEDNE_PORT
      WEDNE_WORKERS: $WEDNE_WORKERS
    volumes:
    - data:/var/wedne

  redis:
    image: redis:7.2-alpine

volumes:
  data:
